#!/usr/bin/env sh
echo "Running lint before push..."
npx --no-install npm run lint

if [ $? -ne 0 ]; then
  echo "Linting failed. Push aborted."
  exit 1
fi
echo "Linting passed. Proceeding with push."